# Generated by Django 4.0.4 on 2022-05-03 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='friends_have_selected',
            field=models.BooleanField(default=True),
        ),
    ]
