# Generated by Django 4.0.4 on 2022-05-03 02:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_meal_friends_have_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='friends_have_selected',
        ),
        migrations.AddField(
            model_name='meal',
            name='friends_have_selected',
            field=models.ManyToManyField(blank=True, related_name='user_has_selected', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='meal',
            name='user_has_selected',
        ),
        migrations.AddField(
            model_name='meal',
            name='user_has_selected',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
