# Generated by Django 4.0.4 on 2022-05-04 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_meal_friends_have_selected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='match',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
