# Generated by Django 4.0.4 on 2022-04-27 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_meal_restaurant_alter_meal_lat_alter_meal_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
