# Generated by Django 4.0.4 on 2022-05-04 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_meal_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='match',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
