# Generated by Django 4.0.4 on 2022-04-28 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_meal_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='radius',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='business_status',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
