# Generated by Django 4.0.4 on 2022-04-28 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_meal_location_alter_meal_radius_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
