# Generated by Django 4.0.4 on 2022-04-30 22:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_restaurant_lat_alter_restaurant_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='no',
            field=models.ManyToManyField(blank=True, related_name='voted_no', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='yes',
            field=models.ManyToManyField(blank=True, related_name='voted_yes', to=settings.AUTH_USER_MODEL),
        ),
    ]
