# Generated by Django 4.0.4 on 2022-05-04 20:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_meal_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='all_users_have_selected',
            field=models.ManyToManyField(blank=True, related_name='all_users_have_selected', to=settings.AUTH_USER_MODEL),
        ),
    ]
