# Generated by Django 4.0.4 on 2022-05-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_meal_all_users_have_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='lat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='lon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
