# Generated by Django 4.0.4 on 2022-05-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_restaurant_no_restaurant_yes'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='num_of_diners',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='yes_count',
            field=models.IntegerField(default=0),
        ),
    ]
