# Generated by Django 4.0.4 on 2022-05-01 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_meal_num_of_diners_restaurant_yes_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='num_of_diners',
        ),
    ]
