# Generated by Django 4.0.4 on 2022-05-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_meal_num_of_diners'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='num_of_diners',
            field=models.IntegerField(default=2),
        ),
    ]
