# Generated by Django 4.0.4 on 2022-05-01 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_meal_num_of_diners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='num_of_diners',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='yes_count',
        ),
    ]
