# Generated by Django 4.0.4 on 2022-05-10 19:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_meal_invitee_names_meal_invitee_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='invitee_names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, null=True), default='', size=None),
        ),
    ]
