# Generated by Django 4.0.4 on 2022-05-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_restaurant_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='number_yes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='number_yes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='pic',
            field=models.URLField(default='https://images.app.goo.gl/RDQtoViqEvvGQc587', max_length=5000),
        ),
    ]
