# Generated by Django 4.0.4 on 2022-05-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_restaurant_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='pic',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='photo_reference',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
