# Generated by Django 4.0.4 on 2022-05-11 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_meal_invitee_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='creator_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
